version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db-pswd
      POSTGRES_USER_FILE: /run/secrets/db-user
    volumes:
      - ./devdatadir:/var/lib/postgresql/data
      #TODO: Load Folder & Content via config
      - ./configs/Postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    secrets:
      - db-user
      - db-pswd
      - db-script-env

  adminer:
    image: adminer
    ports:
      - 8080:8080
  
  worker:
    build: 
      context: ./Images/Go/
      dockerfile: Dockerfile.dev
      #TODO Find a good Way to mirror volumes

  redis-server:
    image: redis:6
    command: 
      - /bin/bash
      - -c
      - /app/redis-make-acl.sh && redis-server /app/redis.conf
    secrets:
      - redis-admin.env
      - redis-worker.env
      - redis-api.env
    configs:
      - source: redis-conf
        target: /app/redis.conf
      - source: redis-make-acl
        target: /app/redis-make-acl.sh


secrets:
  db-user:
    file: ./secrets/postgres/POSTGRES_USER_FILE
  db-pswd:
    file: ./secrets/postgres/POSTGRES_PASSWORD_FILE
  db-script-env: 
    file: ./secrets/postgres/script_env.sh
  # We need granular user secrets for the using applications
  redis-admin.env:
    file: ./secrets/redis/users/admin.env
  redis-worker.env:
    file: ./secrets/redis/users/worker.env
  redis-api.env:
    file: ./secrets/redis/users/api.env


configs:
  redis-conf:
    file: ./configs/redis/REDIS_CONF_FILE
  redis-make-acl:
    file: ./configs/redis/makeACLFile.sh